# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require_relative "../spec/support/factory_bot.rb"

if Rails.env.development?

main_user = User.create(first_name: "main_account", email: "user1@books.com", password: "password123", password_confirmation: "password123", image_url: "https://avatars0.githubusercontent.com/u/18765533?s=460&v=4")

user_one = FactoryBot.create(:user)
user_two = FactoryBot.create(:user)
user_three = FactoryBot.create(:user)
user_four = FactoryBot.create(:user)
user_five = FactoryBot.create(:user)
user_six = FactoryBot.create(:user)
user_seven = FactoryBot.create(:user)
user_eight = FactoryBot.create(:user)
user_nine = FactoryBot.create(:user)
user_ten = FactoryBot.create(:user)
user_eleven = FactoryBot.create(:user)
user_twelve = FactoryBot.create(:user)
user_thirteen = FactoryBot.create(:user)
user_fourteen = FactoryBot.create(:user)
user_fifteen = FactoryBot.create(:user)

book_one = FactoryBot.create(:book)
book_two = FactoryBot.create(:book)
book_three = FactoryBot.create(:book)
book_four = FactoryBot.create(:book)
book_five = FactoryBot.create(:book)
book_six = FactoryBot.create(:book)
book_seven = FactoryBot.create(:book)
book_eight = FactoryBot.create(:book)
book_nine = FactoryBot.create(:book)
book_ten = FactoryBot.create(:book)
book_eleven = FactoryBot.create(:book)
book_twelve = FactoryBot.create(:book)
book_thirteen = FactoryBot.create(:book)
book_fourteen = FactoryBot.create(:book)
book_fifteen = FactoryBot.create(:book)
book_sixteen = FactoryBot.create(:book)
book_seventeen = FactoryBot.create(:book)
book_eighteen = FactoryBot.create(:book)
book_nineteen = FactoryBot.create(:book)
book_twenty = FactoryBot.create(:book)


Shelf.create(user: user_one, book: book_one)
Shelf.create(user: user_one, book: book_three)
Shelf.create(user: user_one, book: book_eighteen)
Shelf.create(user: user_two, book: book_four)
Shelf.create(user: user_two, book: book_four)
Shelf.create(user: user_two, book: book_nineteen)
Shelf.create(user: user_three, book: book_three)
Shelf.create(user: user_four, book: book_two)
Shelf.create(user: user_four, book: book_four)
Shelf.create(user: user_four, book: book_nineteen)
Shelf.create(user: user_five, book: book_one)
Shelf.create(user: user_five, book: book_three)
Shelf.create(user: user_five, book: book_five)
Shelf.create(user: user_five, book: book_twenty)
Shelf.create(user: user_six, book: book_five)
Shelf.create(user: user_six, book: book_six)
Shelf.create(user: user_seven, book: book_one)
Shelf.create(user: user_eight, book: book_nine)
Shelf.create(user: user_nine, book: book_seven)
Shelf.create(user: user_nine, book: book_twenty)
Shelf.create(user: user_ten, book: book_eight)
Shelf.create(user: user_ten, book: book_three)
Shelf.create(user: user_ten, book: book_nine)
Shelf.create(user: user_eleven, book: book_ten)
Shelf.create(user: user_eleven, book: book_twenty)
Shelf.create(user: user_twelve, book: book_eleven)
Shelf.create(user: user_thirteen, book: book_twelve)
Shelf.create(user: user_thirteen, book: book_thirteen)
Shelf.create(user: user_fourteen, book: book_fourteen)
Shelf.create(user: user_fourteen, book: book_fifteen)
Shelf.create(user: user_fourteen, book: book_sixteen)
Shelf.create(user: user_fifteen, book: book_seventeen)

Shelf.create(user: main_user, book: book_one)
Shelf.create(user: main_user, book: book_two)
Shelf.create(user: main_user, book: book_five)
Shelf.create(user: main_user, book: book_eight)
Shelf.create(user: main_user, book: book_nine)
Shelf.create(user: main_user, book: book_twelve)
Shelf.create(user: main_user, book: book_sixteen)
Shelf.create(user: main_user, book: book_seventeen)
Shelf.create(user: main_user, book: book_nineteen)
Shelf.create(user: main_user, book: book_twenty)
Shelf.create(user: main_user, book: book_four)
Shelf.create(user: main_user, book: book_eleven)
Shelf.create(user: main_user, book: book_ten)

end
